WebApplication_4/Entities/Category.cs
namespace WebApplication_4.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
}

WebApplication_4/Entities/Product.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication_4.Entities
{
    public class Product
    {

        public int Id { get; set; }
        [Required(ErrorMessage ="Name CANNOT be NULL!")]
        public string Name { get; set; }
        [Range(1,1000,ErrorMessage ="Price must me higher than 0, lowr than 1000")]
        public decimal Price { get; set; }

    }
}

WebApplication_4/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication_4.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

WebApplication_4/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication_4.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApplication_4/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication_4.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

WebApplication_4/Pages/Product/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication_4.Data;
using WebApplication_4.Entities;
using WebApplication_4.Services;

namespace WebApplication_4.Pages.Product
{
    public class IndexModel : PageModel
    {
        private readonly IProductService _service;

        public IndexModel(IProductService service)
        {
            _service = service;
        }

        public List<Entities.Product> Products { get; set; }

        public async Task<IActionResult> OnGet(int id)
        {
            Products = await _service.GetProductsAsync();

            if (id!=null)
            {
                Product = await _service.GetProductByIdAsync(id);
            }

            return Page();
        }

        public string Info { get; set; }

        [BindProperty]
    public Entities.Product  Product { get; set; }
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Product.Id == 0)
            {
                await _service.Create(Product);
            }
            else
            {
                await _service.Update(Product);
            }

            return RedirectToPage();
        }
        public IActionResult OnPostDelete(Entities.Product product)
        {
            _service.Delete(product);
            return RedirectToAction("Index");
        }
    }
}

WebApplication_4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication_4/Pages/Product/Index.cshtml
@page
@model WebApplication_4.Pages.Product.IndexModel
@{
    
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.Products)
        {
            <tr>
                <td scope="row">@item.Id</td>
                <td scope="row">@item.Name</td>
                <td scope="row">@item.Price</td>
                <td>
                    <form method="get" asp-page-handler="Edit">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button class="btn btn-outline-warning" type="submit">Edit</button>
                    </form>
                </td>
                <td>
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>


@if (Model.Product != null )
{
    <form>
        <input type="hidden" asp-for="Product.Id" />
        <div class="mb-3">
            <label class="form-label">Product Name</label>
            <input asp-for="Product.Name" class="form-control" />
        <span asp-validation-for="Product.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Product Price</label>
            <input asp-for="Product.Price" class="form-control" />
        <span asp-validation-for="Product.Price" class="text-danger"></span>
        </div>
        <button class="btn btn-success" type="submit">Edit</button>
    </form>


}
else
{
    <form class="col-5" method="post">
        <div class="mb-3">
            <label class="form-label">Product Name</label>
            <input asp-for="Product.Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label class="form-label">Product Price</label>
            <input asp-for="Product.Price" class="form-control" />
        </div>
        <button type="submit" class="btn btn-success">Add New Product</button>
    </form>


}

WebApplication_4/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication_4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication_4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebApplication_4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication_4 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>